services:
  redis:
    image: redis:alpine
    command:
    - "--appendonly"
    - "yes"
    volumes:
      - redis-data:/data

  web:
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
      - path: ./.env
      - path: ./override.env
        required: false
  tunnel:
    image: cloudflare/cloudflared
    command:
      - "--no-autoupdate"
      - "tunnel"
      - "--url"
      - "http://web:8080"

volumes:
  redis-data: